############################################################
## Status default config. Valid for ALL languages.
############################################################

## Source for CSS
enablePostCSSProcessing: false
fullCSSSourceFile: "css/src/styles.css"
fullCSSDistFile: "css/dist/styles.css"
postCSSConfigFolder: "themes/clearstatustheme"

# Colors
bodyBackground: "bg-grey-dark"
bodyColor: "text-grey-lighter"
visibleBordersColor: "border-grey-dark"
bordersColor: "border-transparent"
headerBackground: "bg-grey-darkest"
headerColor: "text-grey-lighter"
footerBackground: "bg-grey-darkest"
footerColor: "text-grey-lighter"
componentsBackground: "bg-grey-darker"
componentsColor: "text-grey-darker"
componentsBorders: "bg-transparent"
refreshColor: "text-grey-dark"
paginationLinksColor: "text-grey-darkest"
disabledPaginationLinksColor: "text-grey"

# Severity
defaultSeverityBackground: "bg-grey-dark"
defaultSeverityColor: "text-white"
downSeverityBackground: "bg-red-dark"
downSeverityColor: "text-white"
disruptedSeverityBackground: "bg-orange-dark"
disruptedSeverityColor: "text-white"
monitoringSeverityBackground: "bg-orange"
monitoringSeverityColor: "text-white"
maintenanceSeverityBackground: "bg-grey-light"
maintenanceSeverityColor: "text-white"
okSeverityBackground: "bg-green-dark"
okSeverityColor: "text-white"

# Incident types
scheduledHeaderBackground: "bg-blue-dark"
scheduledHeaderColor: "text-blue"
scheduledHeaderTitleColor: "text-black"
scheduledBodyBackground: "bg-black"
scheduledBodyColor: "text-grey-darkest"
scheduledBodyTitleColor: "text-white"

smallBodyBackground: "bg-grey-dark"
smallBodyColor: "text-grey-darkest"
smallBodyTitleColor: "text-white"

pastBodyBackground: "bg-grey-dark"
pastBodyColor: "text-grey-darkest"
pastBodyTitleColor: "text-white"

# Affected components
affectedBackground: "bg-grey-darkest"
affectedColor: "text-grey-lighter"

# NetlifyCMS support
enableNetlifyCMSSupport: true
netlifySlug: "{{year}}-{{month}}-{{day}}-{{slug}}"
