title: RHG Systems Status Page
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: API
      description: The main API for all internal things.
      link: ""
    - name: Management
      description: RHG Management Framework
      link: ""
    - name: Little R
      description: Little R is made to be an awesome discord bot for easy setup.
        Invite today to enjoy a little buddy next to your server!
      link: https://littler.tk
      group: Robots
    - name: Transistor FM
      description: Transistor FM is a public Discord music bot, made to mimic a radio
        station with tons of jingles and with a variety of music, being
        broadcasted across multiple servers at rapid speeds.
      link: http://radio.rustyrhuskey.tk/
      group: Robots
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: America/New_York
  logo: /images/logo.png
  description_header: Information about RHG's systems operations.<br />Follow us
    <a class='text-grey-darkest' title='Visit my page on Twitter'
    href='https://www.twitter.com/RHGRDev'>on Twitter</a> or subscribe to the <a
    class='text-grey-darkest' href='%s' >RSS</a><br /> feed to be alerted of new
    events.
  copyrightHolder: RHG
  eventsPerPage: 25
  iconType: image/png
  groups:
    - Robots
  icon: /images/logo.png
  description_footer: RHG Status Page
