title: RHG Systems Status
baseURL: https://status.rustyrhuskey.tk
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: This status page provides updated information about our
    systems normal operation, incidents that may happen and their resolution.
  systems:
    - name: API Endpoints
      description: The main API for all internal things.
      link: ""
      group: API
    - name: API Management
      description: RHG Management Framework
      link: ""
      group: API
    - name: Little R
      description: Little R is made to be an awesome discord bot for easy setup.
        Invite today to enjoy a little buddy next to your server!
      link: https://littler.tk
      group: Robots
    - name: Transistor FM
      description: Transistor FM is a public Discord music bot, made to mimic a radio
        station with tons of jingles and with a variety of music, being
        broadcasted across multiple servers at rapid speeds.
      link: http://radio.rustyrhuskey.tk/
      group: Robots
    - name: RHG Bot
      description: RHG is a public Discord bot, made to customize your discord w/
        Custom prefixs, welcome/goodbye messages, and more!
      group: Robots
    - name: Heaven Bot
      group: Robots
      link: https://discord.gg/xn72Gq9
      description: Heaven Bot is a private discord bot made to manage an special
        server from external services.
  dateFormat: "January 2, 2006 at 3:04 PM "
  disqusShortname: 1RHG
  timezoneString: America/New_York
  logo: /images/logo.png
  description_header: Information about RHG's systems operations.<br />Follow me
    <a class='text-grey-darkest' title='Visit my Twitter'
    href='https://www.twitter.com/RHGRDev'>on Twitter</a> or subscribe to the <a
    class='text-grey-darkest' href='%s' >RSS</a><br /> feed to be alerted of new
    events.
  copyrightHolder: RHG
  eventsPerPage: 25
  iconType: image/png
  groups:
    - Robots
    - API
  icon: /images/logo.png
  description_footer: This page is apart of the <a class='text-grey-darkest'
    title='Homepage' href='https://rustyrhuskey.tk'>http://rustyrhuskey.tk</a>
    eco-system.
