############################################################
## Status default config. Valid for ALL languages.
############################################################

## Source for CSS
enablePostCSSProcessing: false
fullCSSSourceFile: "css/src/styles.css"
fullCSSDistFile: "css/dist/styles.css"
postCSSConfigFolder: "themes/clearstatustheme"

# Colors
bodyBackground: "bg-grey-700"
bodyColor: "text-grey-900"
visibleBordersColor: "border-transparent"
bordersColor: "border-transparent"
headerBackground: "bg-grey-700"
headerColor: "text-grey-900"
footerBackground: "bg-grey-400"
footerColor: "text-grey-900"
componentsBackground: "bg-grey-700"
componentsColor: "text-grey-900"
componentsBorders: "border-transparent"
refreshColor: "text-grey-900"
paginationLinksColor: "text-grey-darkest"
disabledPaginationLinksColor: "text-grey-dark"

# Severity
defaultSeverityBackground: "bg-grey-light"
defaultSeverityColor: "text-black"
downSeverityBackground: "bg-red-dark"
downSeverityColor: "text-white"
disruptedSeverityBackground: "bg-orange-dark"
disruptedSeverityColor: "text-white"
monitoringSeverityBackground: "bg-orange"
monitoringSeverityColor: "text-white"
maintenanceSeverityBackground: "bg-grey-light"
maintenanceSeverityColor: "text-black"
okSeverityBackground: "bg-green-dark"
okSeverityColor: "text-white"

# Incident types
scheduledHeaderBackground: "bg-blue-lighter"
scheduledHeaderColor: "text-grey-dark"
scheduledHeaderTitleColor: "text-black"
scheduledBodyBackground: "bg-white"
scheduledBodyColor: "text-grey-darkest"
scheduledBodyTitleColor: "text-black"

smallBodyBackground: "bg-grey-700"
smallBodyColor: "text-grey-900"
smallBodyTitleColor: "text-grey-900"

pastBodyBackground: "bg-grey-700"
pastBodyColor: "text-grey-900"
pastBodyTitleColor: "text-grey-900"

# Affected components
affectedBackground: "bg-grey-700"
affectedColor: "text-grey-900"
